services:
  db:
    build:
      context: .
      dockerfile: Dockerfile_db
    container_name: novelist_database
    restart: always
    ports:
      - 3306:3306
    secrets:
      - mysql_root_password
      - mysql_password
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password
      - MYSQL_DATABASE=sn_project
      - MYSQL_USER=novelist_user
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_password
    volumes:
      - novelist_db:/var/lib/mysql
    user: "mysql"
    networks:
      - novelist_net

  website:
    build: 
      context: .
      dockerfile: Dockerfile_web
    container_name: novelist
    ports:
      - 80:80
      - 443:443
    depends_on:
      - db
    volumes:
      - novels_volume:/var/www/uploaded_novels:rw
      - ./novelist_logs:/var/www/novelist_logs:rw
    secrets:
      - source: mysql_password
        target: /run/www-data_secrets/mysql_password
      - source: smtp_host
        target: /run/www-data_secrets/smtp_host
      - source: smtp_port
        target: /run/www-data_secrets/smtp_port
      - source: smtp_username
        target: /run/www-data_secrets/smtp_username
      - source: smtp_password
        target: /run/www-data_secrets/smtp_password
    user: "www-data"
    networks:
      - novelist_net

volumes:
  novelist_db:
    driver: local
    name: novelist_db

  novels_volume:
    driver: local
    name: novels_volume

networks:
  novelist_net:
    driver: bridge

secrets:
  # MySQL
  mysql_root_password:
    file: ./secrets/mysql_root_password.txt

  mysql_password:
    file: ./secrets/mysql_password.txt

  # SMTP
  smtp_host:
    file: ./secrets/smtp_host.txt

  smtp_port:
    file: ./secrets/smtp_port.txt

  smtp_username:
    file: ./secrets/smtp_username.txt

  smtp_password:
    file: ./secrets/smtp_password.txt